Fixes RuntimeError thrown by finalize_properties in Dynamic UI Fields.
This issue only affects Python 3.0+

RuntimeError: dictionary changed size during iteration is thrown
by the function mentioned above, because it iterates over kwargs
while deleting entries from it.

Change-Id: I4523296be770bddaeffff7f7ded9501ccc42cbdd
Closes-Bug: #1638928