Fix package import fails due to QueryDict immutable
get_form_step_data QueryDict became immutable. cause the error:
AttributeError: This QueryDict instance is immutable
Make a copy for the QueryDict.

Change-Id: I6bd2908e83d00fec7b3d292d94aef4718fbe22d0
Closes-Bug: #1707527